---
abstract: 'Business::CPI models for Catalyst'
author:
  - 'André Walker <andre@andrewalker.net>'
build_requires:
  File::Path: 2
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-CPI
requires:
  Business::CPI: 0.5
  Catalyst::Runtime: 5.8
  Module::Pluggable: 0
  Moo::Role: 0
  perl: 5.008
resources:
  repository: git://github.com/andrewalker/p5-catalyst-model-cpi.git
version: 0.01
